name: gh-pages

on:
  push:
    branches:
      - main

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      - name: Install dependencies
        run: pnpm install
        working-directory: ./frontend

      - name: Build Vite
        run: pnpm build
        working-directory: ./frontend

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist
